---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rukpak-system
  name: core
  labels:
    app: core
spec:
  template:
    spec:
      volumes:
        - emptyDir: {}
          name: bundle-cache
        - emptyDir: {}
          name: upload-cache
        - name: certs
          secret:
            optional: false
            secretName: core-cert
      containers:
        - name: kube-rbac-proxy
          volumeMounts:
            - name: certs
              mountPath: /etc/pki/tls
        - name: manager
          volumeMounts:
            - mountPath: /var/cache/bundles
              name: bundle-cache
            - mountPath: /var/cache/uploads
              name: upload-cache
            - mountPath: /etc/pki/tls
              name: certs
