---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rukpak-system
  name: helm-provisioner
  labels:
    app: helm-provisioner
spec:
  template:
    spec:
      volumes:
        - name: bundle-cache
          emptyDir: {}
        - name: certs
          secret:
            secretName: helm-provisioner-cert
            optional: false
      containers:
        - name: kube-rbac-proxy
          volumeMounts:
            - name: certs
              mountPath: /etc/pki/tls
        - name: manager
          volumeMounts:
            - name: bundle-cache
              mountPath: /var/cache/bundles
            - name: certs
              mountPath: /etc/pki/tls
